[package]
name = "AdventOfRust"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
const_format = "0.2.33"
ndarray = "0.16.1"
regex = "1.11.1"
